export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "SpecForge AI API",
    version: "1.0.0",
    description: "Requirement-to-task planning API",
  },
  servers: [{ url: "/api/v1" }],
  tags: [
    { name: "Operations" }, { name: "Auth" }, { name: "Projects" }, { name: "Requirements" },
    { name: "AI Analysis" }, { name: "AI Jobs" }, { name: "Tasks" }, { name: "Sprints" }, { name: "Usage" }, { name: "Exports" }, { name: "Integrations" }, { name: "Collaboration" }, { name: "Analytics" },
  ],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      Error: { type: "object", properties: { success: { type: "boolean", example: false }, error: { type: "object", properties: { message: { type: "string" } } } } },
      Login: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } },
      Register: { type: "object", required: ["name", "email", "password"], properties: { name: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } },
      ProjectInput: { type: "object", required: ["workspaceId", "name", "key"], properties: { workspaceId: { type: "string", format: "uuid" }, name: { type: "string" }, key: { type: "string" }, description: { type: "string" } } },
      RequirementInput: { type: "object", required: ["title", "content"], properties: { title: { type: "string" }, content: { type: "string" }, status: { type: "string", enum: ["DRAFT", "READY", "NEEDS_CLARIFICATION", "APPROVED"] } } },
    },
  },
  paths: {
    "/health": { get: { tags: ["Operations"], summary: "Liveness health check", responses: { "200": { description: "API is alive" } } } },
    "/ready": { get: { tags: ["Operations"], summary: "Readiness check", responses: { "200": { description: "API dependencies are ready" } } } },
    "/auth/register": { post: { tags: ["Auth"], summary: "Register", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Register" } } } }, responses: { "201": { description: "Registered" } } } },
    "/auth/login": { post: { tags: ["Auth"], summary: "Login", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Login" } } } }, responses: { "200": { description: "Logged in" } } } },
    "/auth/me": { get: { tags: ["Auth"], summary: "Current user", security: [{ bearerAuth: [] }], responses: { "200": { description: "Current user" } } } },
    "/projects": {
      post: { tags: ["Projects"], summary: "Create project", security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ProjectInput" } } } }, responses: { "201": { description: "Created" } } },
      get: { tags: ["Projects"], summary: "List projects", security: [{ bearerAuth: [] }], parameters: [{ in: "query", name: "workspaceId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "search", schema: { type: "string" } }, { in: "query", name: "status", schema: { type: "string" } }, { in: "query", name: "page", schema: { type: "integer", minimum: 1 } }, { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "Projects" } } },
    },
    "/projects/{projectId}/requirements": {
      post: { tags: ["Requirements"], summary: "Create requirement", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/RequirementInput" } } } }, responses: { "201": { description: "Created" } } },
      get: { tags: ["Requirements"], summary: "List requirements", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Requirements" } } },
    },
    "/requirements/{requirementId}/analyze": { post: { tags: ["AI Analysis"], summary: "Analyze requirement", description: "Pass async=true to queue requirement analysis and poll the returned AI job.", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "requirementId", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { force: { type: "boolean" }, async: { type: "boolean" } } } } } }, responses: { "201": { description: "Analyzed" }, "202": { description: "Queued" } } } },
    "/analyses/{analysisId}/feedback": { post: { tags: ["Analytics"], summary: "Submit AI analysis feedback", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "analysisId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "201": { description: "Feedback event captured" } } } },
    "/analyses/{analysisId}/tasks/generate": { post: { tags: ["Tasks"], summary: "Generate tasks", description: "Pass async=true to queue task generation and poll the returned AI job.", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "analysisId", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { regenerate: { type: "boolean" }, async: { type: "boolean" } } } } } }, responses: { "201": { description: "Generated" }, "202": { description: "Queued" } } } },
    "/ai-jobs/{jobId}": { get: { tags: ["AI Jobs"], summary: "Get AI job status", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "jobId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "AI job" } } } },
    "/projects/{projectId}/ai-jobs": { get: { tags: ["AI Jobs"], summary: "List project AI jobs", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "status", schema: { type: "string" } }, { in: "query", name: "type", schema: { type: "string" } }, { in: "query", name: "page", schema: { type: "integer", minimum: 1 } }, { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "AI jobs" } } } },
    "/projects/{projectId}/tasks": { get: { tags: ["Tasks"], summary: "List project tasks", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "status", schema: { type: "string" } }, { in: "query", name: "type", schema: { type: "string" } }, { in: "query", name: "priority", schema: { type: "string" } }, { in: "query", name: "sprintId", schema: { type: "string", format: "uuid" } }, { in: "query", name: "search", schema: { type: "string" } }, { in: "query", name: "page", schema: { type: "integer", minimum: 1 } }, { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "Tasks" } } } },
    "/tasks/{taskId}/comments": {
      get: { tags: ["Collaboration"], summary: "List task comments", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "taskId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Comments" } } },
      post: { tags: ["Collaboration"], summary: "Create task comment", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "taskId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "201": { description: "Comment created" } } },
    },
    "/projects/{projectId}/activity": { get: { tags: ["Collaboration"], summary: "List project activity", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "Activity" } } } },
    "/projects/{projectId}/members": { get: { tags: ["Collaboration"], summary: "List project workspace members", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Members" } } } },
    "/projects/{projectId}/invitations": {
      get: { tags: ["Collaboration"], summary: "List workspace invitations for a project", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Invitations" } } },
      post: { tags: ["Collaboration"], summary: "Create workspace invitation", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "201": { description: "Invitation created with one-time acceptance token" } } },
    },
    "/invitations/{invitationId}": { delete: { tags: ["Collaboration"], summary: "Cancel workspace invitation", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "invitationId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Invitation cancelled" } } } },
    "/invitations/accept": { post: { tags: ["Collaboration"], summary: "Accept workspace invitation", security: [{ bearerAuth: [] }], responses: { "200": { description: "Invitation accepted" } } } },
    "/notifications": { get: { tags: ["Collaboration"], summary: "List current user notifications", security: [{ bearerAuth: [] }], parameters: [{ in: "query", name: "unreadOnly", schema: { type: "boolean" } }, { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100 } }], responses: { "200": { description: "Notifications" } } } },
    "/notifications/{notificationId}/read": { patch: { tags: ["Collaboration"], summary: "Mark notification read", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "notificationId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Notification updated" } } } },
    "/analytics/events": { post: { tags: ["Analytics"], summary: "Track product analytics event", security: [{ bearerAuth: [] }], responses: { "201": { description: "Event captured" } } } },
    "/projects/{projectId}/analytics/summary": { get: { tags: ["Analytics"], summary: "Get project analytics summary", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "days", schema: { type: "integer", minimum: 1, maximum: 365 } }], responses: { "200": { description: "Analytics summary" } } } },
    "/projects/{projectId}/usage": { get: { tags: ["Usage"], summary: "Get project monthly usage and quotas", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Usage summary" } } } },
    "/projects/{projectId}/exports/tasks.csv": { get: { tags: ["Exports"], summary: "Export project tasks as CSV", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "status", schema: { type: "string" } }, { in: "query", name: "type", schema: { type: "string" } }, { in: "query", name: "priority", schema: { type: "string" } }, { in: "query", name: "sprintId", schema: { type: "string", format: "uuid" } }, { in: "query", name: "search", schema: { type: "string" } }], responses: { "200": { description: "CSV file" } } } },
    "/projects/{projectId}/exports/sprints.csv": { get: { tags: ["Exports"], summary: "Export project sprints as CSV", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "CSV file" } } } },
    "/projects/{projectId}/exports/planning.json": { get: { tags: ["Exports"], summary: "Export complete planning package as JSON", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Planning package JSON" } } } },
    "/projects/{projectId}/exports/planning.pdf": { get: { tags: ["Exports"], summary: "Export planning package as PDF", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Planning package PDF" } } } },
    "/projects/{projectId}/integrations": {
      get: { tags: ["Integrations"], summary: "List project integrations", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }, { in: "query", name: "provider", schema: { type: "string" } }, { in: "query", name: "status", schema: { type: "string" } }], responses: { "200": { description: "Integrations" } } },
      post: { tags: ["Integrations"], summary: "Create project integration", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "201": { description: "Integration created" } } },
    },
    "/integrations/{integrationId}": {
      patch: { tags: ["Integrations"], summary: "Update integration", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "integrationId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Integration updated" } } },
      delete: { tags: ["Integrations"], summary: "Delete integration", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "integrationId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "204": { description: "Integration deleted" } } },
    },
    "/projects/{projectId}/sprints": {
      post: { tags: ["Sprints"], summary: "Create sprint", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "201": { description: "Created" } } },
      get: { tags: ["Sprints"], summary: "List sprints", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "projectId", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Sprints" } } },
    },
  },
};
