import { Router } from "express";
import { authRouter } from "../modules/auth/auth.route.js";
import { aiAnalysisRouter } from "../modules/ai-analysis/ai-analysis.route.js";
import { aiJobRouter } from "../modules/ai-jobs/ai-job.route.js";
import { analyticsRouter } from "../modules/analytics/analytics.route.js";
import { collaborationRouter } from "../modules/collaboration/collaboration.route.js";
import { exportRouter } from "../modules/exports/export.route.js";
import { integrationRouter } from "../modules/integrations/integration.route.js";
import { notificationRouter } from "../modules/notifications/notification.route.js";
import { operationsRouter } from "../modules/operations/operations.route.js";
import { projectRouter } from "../modules/projects/project.route.js";
import { projectRequirementRouter, requirementRouter } from "../modules/requirements/requirement.route.js";
import { sprintRouter } from "../modules/sprints/sprint.route.js";
import { taskRouter } from "../modules/tasks/task.route.js";
import { usageRouter } from "../modules/usage/usage.route.js";

export const apiRouter = Router();
apiRouter.use(operationsRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/projects", projectRouter);
apiRouter.use("/projects/:projectId/requirements", projectRequirementRouter);
apiRouter.use("/requirements", requirementRouter);
apiRouter.use(aiAnalysisRouter);
apiRouter.use(aiJobRouter);
apiRouter.use(taskRouter);
apiRouter.use(sprintRouter);
apiRouter.use(usageRouter);
apiRouter.use(exportRouter);
apiRouter.use(integrationRouter);
apiRouter.use(collaborationRouter);
apiRouter.use(notificationRouter);
apiRouter.use(analyticsRouter);
